# Generated by Django 4.2.30 on 2026-06-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeGrowerGroup',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('formal_org', 'Formal Organization'), ('community_group', 'Community Group'), ('informal_group', 'Informal Group')], default='informal_group', help_text='Classification of the tree grower group', max_length=30)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='group_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tree Grower Group',
                'verbose_name_plural': 'Tree Grower Groups',
                'ordering': ['group_name'],
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('CityENROHead', 'City ENRO Head'), ('OnsiteInspector', 'Onsite Inspector'), ('GISSpecialist', 'GIS Specialist'), ('treeGrowers', 'Tree Growers'), ('DataManager', 'DataManager')], default='OnsiteInspector', max_length=30),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_role'], name='accounts_us_user_ro_29a8b9_idx'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddField(
            model_name='treegrowergroup',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tree_grower_group', to='accounts.user'),
        ),
        migrations.AddIndex(
            model_name='treegrowergroup',
            index=models.Index(fields=['group_type'], name='accounts_tr_group_t_a3fd30_idx'),
        ),
    ]
