# Generated by Django 5.2.8 on 2025-11-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('CityENROHead', 'City ENRO Head'), ('FieldOfficer', 'Field Officer'), ('AFA', 'Agricultural Field Assessor (AFA)'), ('GISSpecialist', 'GIS Specialist'), ('MonitoringOfficer', 'Monitoring Officer')], default='FieldOfficer', max_length=30),
        ),
    ]
