# Generated by Django 4.2.30 on 2026-07-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_role', models.CharField(blank=True, help_text='Broadcast to all users with this role (only if user is NULL)', max_length=30, null=True)),
                ('type', models.CharField(choices=[('alert', 'Alert'), ('success', 'Success'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, help_text='Route to navigate to when clicked (e.g., /DataManager/applications/123)', max_length=255, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Specific user. NULL = general notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='accounts_no_user_id_b29cd4_idx'), models.Index(fields=['target_role', 'is_read', '-created_at'], name='accounts_no_target__9c1f8c_idx')],
            },
        ),
    ]
