# Generated by Django 4.2.30 on 2026-05-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('reforestation_areas', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_onsite_inspector',
            fields=[
                ('assigned_onsite_inspector_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reforestation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_inspections', to='reforestation_areas.reforestation_areas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_inspections', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Field_assessment',
            fields=[
                ('field_assessment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(choices=[('meta_data', 'Meta Data (Area Level)'), ('safety', 'Safety (MCDA Layer 1)'), ('boundary_verification', 'Boundary Verification (MCDA Layer 2)'), ('survivability', 'Survivability (MCDA Layer 3)')], default='pre_assessment', max_length=30)),
                ('assessment_date', models.DateField(blank=True, help_text='Date inspector conducted the assessment.', null=True)),
                ('location', models.JSONField(blank=True, help_text='Optional GPS: {latitude, longitude, gps_accuracy_meters}. Null = meeting-based collection.', null=True)),
                ('field_assessment_data', models.JSONField(default=dict, help_text='Layer-specific observational data collected by the onsite inspector.')),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_onsite_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_assessments', to='Field_assessment.assigned_onsite_inspector')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_assessment', to='sites.sites')),
            ],
        ),
        migrations.CreateModel(
            name='Field_assessment_images',
            fields=[
                ('field_assessment_images_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(blank=True, choices=[('meta_data', 'Meta Data (Area Level)'), ('safety', 'Safety (MCDA Layer 1)'), ('boundary_verification', 'Boundary Verification (MCDA Layer 2)'), ('survivability', 'Survivability (MCDA Layer 3)')], default='pre_assessment', help_text='Which assessment layer this image supports.', max_length=30, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='field_assessments/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Field_assessment.field_assessment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assigned_onsite_inspector',
            constraint=models.UniqueConstraint(fields=('user', 'reforestation_area'), name='unique_user_reforestation_assignment'),
        ),
    ]
