# Generated by Django 4.2.30 on 2026-05-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field_assessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='field_assessment',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='field_assessment_images',
            name='caption',
        ),
        migrations.AddField(
            model_name='field_assessment_images',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Per-photo observation/note'),
        ),
        migrations.AddField(
            model_name='field_assessment_images',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude from Geocam', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='field_assessment_images',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude from Geocam', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='field_assessment',
            name='field_assessment_data',
            field=models.JSONField(default=dict, help_text='Stores overall notes, location context, and categorical selections for Meta, Safety, Survivability, and Boundary layers.'),
        ),
        migrations.AlterField(
            model_name='field_assessment_images',
            name='layer',
            field=models.CharField(blank=True, choices=[('meta_land_title', 'Meta: Land Title'), ('meta_tax_decl', 'Meta: Tax Declaration'), ('meta_other_doc', 'Meta: Other Document'), ('safety_flood', 'Safety: Flood'), ('safety_landslide', 'Safety: Landslide'), ('safety_erosion', 'Safety: Soil Erosion'), ('safety_other', 'Safety: Other Observation'), ('surv_soil', 'Survivability: Soil'), ('surv_water', 'Survivability: Water Availability'), ('surv_animal', 'Survivability: Animal Presence'), ('surv_slope', 'Survivability: Slope'), ('bound_verification', 'Boundary: Verification')], help_text='Strict layer code for filtering and MCDA mapping.', max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='field_assessment_images',
            index=models.Index(fields=['layer'], name='idx_layer'),
        ),
        migrations.AddIndex(
            model_name='field_assessment_images',
            index=models.Index(fields=['field_assessment', 'layer'], name='idx_assessment_layer'),
        ),
    ]
