# Generated by Django 4.2.30 on 2026-06-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reforestation_areas', '0004_remove_hazardpronesite_reforestation_area_and_more'),
        ('Field_assessment', '0002_alter_field_assessment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_assessment',
            name='reforestation_area',
            field=models.ForeignKey(blank=True, help_text='Filled for General assessments. Can be derived from inspector assignment, but stored here for direct querying.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_field_assessments', to='reforestation_areas.reforestation_areas'),
        ),
        migrations.AlterField(
            model_name='field_assessment',
            name='assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field_assessment',
            name='field_assessment_data',
            field=models.JSONField(default=dict, help_text='Stores overall notes, location context, and categorical selections.'),
        ),
        migrations.AlterField(
            model_name='field_assessment',
            name='location',
            field=models.JSONField(blank=True, help_text='Optional GPS: {latitude, longitude, gps_accuracy_meters}', null=True),
        ),
        migrations.AlterField(
            model_name='field_assessment_images',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='field_assessment_images',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='field_assessment_images',
            name='layer',
            field=models.CharField(blank=True, choices=[('meta_land_title', 'Meta: Land Title'), ('meta_tax_decl', 'Meta: Tax Declaration'), ('meta_other_doc', 'Meta: Other Document'), ('safety_flood', 'Safety: Flood'), ('safety_landslide', 'Safety: Landslide'), ('safety_erosion', 'Safety: Soil Erosion'), ('safety_other', 'Safety: Other Observation'), ('surv_soil', 'Survivability: Soil'), ('surv_water', 'Survivability: Water Availability'), ('surv_animal', 'Survivability: Animal Presence'), ('surv_slope', 'Survivability: Slope'), ('bound_verification', 'Boundary: Verification')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='field_assessment_images',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
