# Generated by Django 4.2.30 on 2026-06-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field_assessment', '0003_field_assessment_reforestation_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field_assessment',
            name='reforestation_area',
        ),
    ]
