# Generated by Django 4.2.30 on 2026-06-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land_classifications', '0001_initial'),
        ('animals', '0001_initial'),
        ('Field_assessment', '0004_remove_field_assessment_reforestation_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_assessment',
            name='land_classification',
            field=models.ForeignKey(blank=True, help_text='Official land classification per DENR/CENRO records', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_assessments', to='land_classifications.landclassification'),
        ),
        migrations.CreateModel(
            name='FieldAssessmentAnimal',
            fields=[
                ('field_assessment_animal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_relations', to='animals.animal')),
                ('field_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_relations', to='Field_assessment.field_assessment')),
            ],
            options={
                'db_table': 'field_assessment_animals',
                'ordering': ['-created_at'],
                'unique_together': {('field_assessment', 'animal')},
            },
        ),
        migrations.AddField(
            model_name='field_assessment',
            name='animals_present',
            field=models.ManyToManyField(blank=True, help_text='Animals observed during field assessment', related_name='field_assessments', through='Field_assessment.FieldAssessmentAnimal', to='animals.animal'),
        ),
    ]
