# Generated by Django 4.2.30 on 2026-06-26 10:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field_assessment', '0005_field_assessment_land_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field_assessment_images',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
