# Generated by Django 4.2.30 on 2026-07-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field_assessment', '0006_alter_field_assessment_images_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field_assessment_images',
            name='layer',
            field=models.CharField(blank=True, choices=[('meta_other_doc', 'Meta: Other Document'), ('safety_flood', 'Safety: Flood'), ('safety_landslide', 'Safety: Landslide'), ('safety_erosion', 'Safety: Soil Erosion'), ('safety_other', 'Safety: Other Observation'), ('surv_soil', 'Survivability: Soil'), ('surv_water', 'Survivability: Water Availability'), ('surv_animal', 'Survivability: Animal Presence'), ('surv_slope', 'Survivability: Slope'), ('bound_verification', 'Boundary: Verification')], max_length=30, null=True),
        ),
    ]
