# Generated by Django 4.2.30 on 2026-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field_assessment', '0007_alter_field_assessment_images_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_assessment',
            name='sent_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the assessment was officially sent/submitted.', null=True),
        ),
    ]
