# Generated by Django 4.2.30 on 2026-09-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field_assessment', '0008_field_assessment_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_assessment',
            name='title',
            field=models.CharField(blank=True, help_text="A short, descriptive title to identify this field assessment (e.g., 'Baseline Survey - Sector A').", max_length=255, null=True, unique=True),
        ),
    ]
