# Generated by Django 4.2.30 on 2026-06-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardArea',
            fields=[
                ('hazard_area_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hazard_type', models.CharField(choices=[('LANDSLIDE', 'Landslide'), ('FLOOD', 'Flood'), ('EARTHQUAKE', 'Earthquake'), ('VOLCANIC', 'Volcanic Hazard'), ('STORM_SURGE', 'Storm Surge'), ('OTHER', 'Other')], default='LANDSLIDE', max_length=20)),
                ('polygon', models.JSONField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='hazard_areas', to='barangay.barangay')),
            ],
            options={
                'verbose_name': 'Hazard Area',
                'verbose_name_plural': 'Hazard Areas',
                'db_table': 'hazard_areas',
                'ordering': ['hazard_type', 'name'],
            },
        ),
    ]
