# Generated by Django 4.2.30 on 2026-05-13 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land_classifications', '0001_initial'),
        ('accounts', '0001_initial'),
        ('barangay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reforestation_areas',
            fields=[
                ('reforestation_area_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('area_img', models.ImageField(blank=True, null=True, upload_to='areas/')),
                ('legality', models.CharField(blank=True, choices=[('pending', 'Pending'), ('legal', 'Legal'), ('illegal', 'Illegal')], default='pending', max_length=20)),
                ('pre_assessment_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reforestation_data', models.JSONField(blank=True, help_text='GIS Specialist manual validation JSON. Stored after right-panel review.', null=True)),
                ('safety', models.CharField(blank=True, choices=[('safe', 'Low Risk'), ('slightly', 'Slightly Unsafe'), ('moderate', 'Moderate Risk'), ('danger', 'High Risk')], default='danger', max_length=20)),
                ('polygon_coordinate', models.JSONField(blank=True, null=True)),
                ('coordinate', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reforestation_areas', to='barangay.barangay')),
                ('land_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reforesatation_areas', to='land_classifications.landclassification')),
            ],
        ),
        migrations.CreateModel(
            name='Potential_sites',
            fields=[
                ('potential_sites_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(blank=True, max_length=50)),
                ('polygon_coordinates', models.JSONField(blank=True, null=True)),
                ('area_hectares', models.FloatField(default=0)),
                ('avg_ndvi', models.FloatField(default=0)),
                ('suitability_score', models.FloatField(default=0)),
                ('ndvi_threshold', models.FloatField(default=0.41)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('reforestation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_sites', to='reforestation_areas.reforestation_areas')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitDocument',
            fields=[
                ('permit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('barangay_clearance', 'Barangay Clearance'), ('lgu_endorsement', 'LGU Endorsement'), ('denr_permit', 'DENR Permit'), ('landowner_consent', 'Landowner Consent'), ('other', 'Other')], max_length=30)),
                ('permit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='permits/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('verification_notes', models.TextField(blank=True, help_text='GIS Specialist notes on why this permit was accepted', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reforestation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_documents', to='reforestation_areas.reforestation_areas')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='GIS Specialist who verified & uploaded', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
