# Generated by Django 4.2.30 on 2026-05-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land_classifications', '0001_initial'),
        ('accounts', '0001_initial'),
        ('reforestation_areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitdocument',
            options={'ordering': ['reforestation_area', '-uploaded_at'], 'verbose_name_plural': 'Permit Documents'},
        ),
        migrations.AlterModelOptions(
            name='reforestation_areas',
            options={'ordering': ['name'], 'verbose_name_plural': 'Reforestation Areas'},
        ),
        migrations.RemoveField(
            model_name='reforestation_areas',
            name='legality',
        ),
        migrations.RemoveField(
            model_name='reforestation_areas',
            name='pre_assessment_status',
        ),
        migrations.RemoveField(
            model_name='reforestation_areas',
            name='reforestation_data',
        ),
        migrations.RemoveField(
            model_name='reforestation_areas',
            name='safety',
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='source_assessment_id',
            field=models.BigIntegerField(blank=True, help_text='ID from field_assessment.FieldAssessment (if uploaded by inspector)', null=True),
        ),
        migrations.AddField(
            model_name='reforestation_areas',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='permitdocument',
            name='document_type',
            field=models.CharField(choices=[('land_title', 'Land Title'), ('tax_declaration', 'Tax Declaration'), ('barangay_clearance', 'Barangay Clearance'), ('lgu_endorsement', 'LGU Endorsement'), ('denr_permit', 'DENR Permit'), ('landowner_consent', 'Landowner Consent'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='permitdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='permitdocument',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes on this document', null=True),
        ),
        migrations.AlterField(
            model_name='reforestation_areas',
            name='coordinate',
            field=models.JSONField(blank=True, help_text='Center marker coordinate', null=True),
        ),
        migrations.AlterField(
            model_name='reforestation_areas',
            name='land_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reforestation_areas', to='land_classifications.landclassification'),
        ),
        migrations.AlterField(
            model_name='reforestation_areas',
            name='polygon_coordinate',
            field=models.JSONField(blank=True, help_text='Polygon geometry for GIS', null=True),
        ),
        migrations.CreateModel(
            name='AreaMetaDataVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verified_security_concerns', models.JSONField(blank=True, help_text="List of confirmed concerns: ['Armed Threat', 'Land Conflict']", null=True)),
                ('verified_accessibility', models.JSONField(blank=True, help_text="{'type': 'Vehicle', 'road_condition': '2km dirt road, 4x4 required'}", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('draft', 'Draft'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decision_note', models.TextField(blank=True, help_text='Reason for acceptance/rejection', null=True)),
                ('referenced_assessment_ids', models.JSONField(blank=True, help_text='List of field_assessment.FieldAssessment IDs used as evidence', null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reforestation_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_verification', to='reforestation_areas.reforestation_areas')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
                ('verified_land_classification', models.ForeignKey(blank=True, help_text='Final confirmed land classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_areas', to='land_classifications.landclassification')),
            ],
            options={
                'verbose_name': 'Area Meta Data Verification',
                'verbose_name_plural': 'Area Meta Data Verifications',
            },
        ),
    ]
