# Generated by Django 4.2.30 on 2026-06-06 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reforestation_areas', '0002_alter_permitdocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardProneSite',
            fields=[
                ('hazard_site_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(blank=True, max_length=50)),
                ('polygon_coordinates', models.JSONField(blank=True, null=True)),
                ('area_hectares', models.FloatField(default=0)),
                ('hazard_type', models.CharField(choices=[('landslide', 'Landslide'), ('flood', 'Flood'), ('wildfire', 'Wildfire')], max_length=20)),
                ('risk_class', models.IntegerField(default=4, help_text='4 (High) or 5 (Very High)')),
                ('avg_hazard_index', models.FloatField(default=0, help_text='Average LSI/FSI/WSI score')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('reforestation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_prone_sites', to='reforestation_areas.reforestation_areas')),
            ],
            options={
                'verbose_name_plural': 'Hazard Prone Sites',
                'ordering': ['-created_at'],
            },
        ),
    ]
