# Generated by Django 4.2.30 on 2026-06-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reforestation_areas', '0003_hazardpronesite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardpronesite',
            name='reforestation_area',
        ),
        migrations.RemoveField(
            model_name='permitdocument',
            name='reforestation_area',
        ),
        migrations.RemoveField(
            model_name='permitdocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='potential_sites',
            name='reforestation_area',
        ),
        migrations.RemoveField(
            model_name='reforestation_areas',
            name='area_img',
        ),
        migrations.RemoveField(
            model_name='reforestation_areas',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='reforestation_areas',
            name='land_classification',
        ),
        migrations.RemoveField(
            model_name='reforestation_areas',
            name='polygon_coordinate',
        ),
        migrations.DeleteModel(
            name='AreaMetaDataVerification',
        ),
        migrations.DeleteModel(
            name='HazardProneSite',
        ),
        migrations.DeleteModel(
            name='PermitDocument',
        ),
        migrations.DeleteModel(
            name='Potential_sites',
        ),
    ]
