# Generated by Django 4.2.30 on 2026-06-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0001_initial'),
        ('reforestation_areas', '0004_remove_hazardpronesite_reforestation_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reforestation_areas',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reforestation_areas', to='barangay.barangay'),
        ),
    ]
