# Generated by Django 4.2.30 on 2026-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ormoc_City',
            fields=[
                ('ormoc_city_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marker', models.JSONField()),
                ('polygon', models.JSONField()),
            ],
        ),
    ]
