# Generated by Django 4.2.30 on 2026-05-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandClassification',
            fields=[
                ('land_classification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('for_reforestation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classified_areas',
            fields=[
                ('classified_area_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('polygon', models.JSONField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='classified_areas', to='barangay.barangay')),
                ('land_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_areas', to='land_classifications.landclassification')),
            ],
        ),
    ]
