# Generated by Django 4.2.30 on 2026-07-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_classifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified_areas',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='landclassification',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
