# Generated by Django 4.2.30 on 2026-07-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_classifications', '0002_alter_classified_areas_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landclassification',
            options={'ordering': ['name'], 'verbose_name': 'Land Classification', 'verbose_name_plural': 'Land Classifications'},
        ),
        migrations.RemoveField(
            model_name='landclassification',
            name='for_reforestation',
        ),
        migrations.AddField(
            model_name='landclassification',
            name='ownership_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='private', help_text='Land ownership classification (Public or Private).', max_length=20),
        ),
    ]
