# Generated by Django 4.2.30 on 2026-09-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land_classifications', '0003_alter_landclassification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified_areas',
            name='land_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classified_areas', to='land_classifications.landclassification'),
        ),
    ]
