# Generated by Django 4.2.30 on 2026-05-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tree_species', '0001_initial'),
        ('reforestation_areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('site_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('under_monitoring', 'Under Monitoring')], db_index=True, default='pending', max_length=20)),
                ('name', models.CharField(default='Unnamed Site', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='Pin site to top of dashboard for priority tracking.')),
                ('polygon_coordinates', models.JSONField(blank=True, help_text='GeoJSON polygon array [[lat,lng], ...] — boundary drawn by GIS Specialist.', null=True)),
                ('center_coordinate', models.JSONField(blank=True, help_text='Single point [lat, lng] — auto-computed centroid of polygon.', null=True)),
                ('marker_coordinate', models.JSONField(blank=True, help_text='Optional GPS verification point [lat, lng] for boundary corner reference.', null=True)),
                ('ndvi_value', models.FloatField(blank=True, help_text='Raw NDVI from satellite. Target: 0.2–0.4 (degraded/grassland).', null=True)),
                ('total_area_hectares', models.FloatField(default=0.0, help_text='Calculated from polygon_coordinates by GIS Specialist.')),
                ('total_seedlings_planted', models.IntegerField(default=0, help_text='Updated post-planting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reforestation_area', models.ForeignKey(help_text="Parent area. Sites can only be created if area.pre_assessment_status = 'approved'", on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='reforestation_areas.reforestation_areas')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site_species_recommendation',
            fields=[
                ('site_species_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('priority_rank', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_recommendations', to='sites.sites')),
                ('tree_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for_sites', to='tree_species.tree_species')),
            ],
            options={
                'verbose_name': 'Site Species Recommendation',
                'verbose_name_plural': 'Site Species Recommendations',
                'ordering': ['priority_rank'],
            },
        ),
        migrations.CreateModel(
            name='Site_images',
            fields=[
                ('site_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('layer_tag', models.CharField(choices=[('safety', 'Safety'), ('boundary_verification', 'Boundary Verification'), ('survivability', 'Survivability'), ('general', 'General')], default='general', max_length=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='sites/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_images', to='sites.sites')),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
                'ordering': ['layer_tag', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site_data',
            fields=[
                ('site_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='True = active/official record. False = historical archive (read-only).')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('validated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('site_data', models.JSONField(default=dict)),
                ('field_assessment_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_data_versions', to='sites.sites')),
            ],
            options={
                'verbose_name': 'Site MCDA Data',
                'verbose_name_plural': 'Site MCDA Data',
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='sites',
            constraint=models.UniqueConstraint(fields=('reforestation_area', 'name'), name='unique_site_name_per_area'),
        ),
        migrations.AddConstraint(
            model_name='site_species_recommendation',
            constraint=models.UniqueConstraint(fields=('site', 'tree_species'), name='unique_species_per_site'),
        ),
        migrations.AddConstraint(
            model_name='site_data',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('site',), name='unique_current_site_data_per_site'),
        ),
    ]
