# Generated by Django 4.2.30 on 2026-05-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_data',
            options={'ordering': ['-version'], 'verbose_name': 'Site Validation Data', 'verbose_name_plural': 'Site Validation Data'},
        ),
        migrations.AlterField(
            model_name='site_data',
            name='field_assessment_snapshot',
            field=models.JSONField(default=dict, help_text='Snapshot of field assessment IDs used as evidence'),
        ),
        migrations.AlterField(
            model_name='site_data',
            name='site_data',
            field=models.JSONField(default=dict, help_text='\n        {\n          "safety": { "decision_note": "Text..." },\n          "survivability": { "decision_note": "Text..." },\n          "final_decision": "ACCEPT" | "REJECT",\n          "final_decision_note": "Overall explanation...",\n          "validated_at": "...",\n          "validated_by": "..."\n        }\n        '),
        ),
        migrations.AlterField(
            model_name='site_images',
            name='layer_tag',
            field=models.CharField(choices=[('safety', 'Safety'), ('survivability', 'Survivability'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
