# Generated by Django 4.2.30 on 2026-06-08 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reforestation_areas', '0004_remove_hazardpronesite_reforestation_area_and_more'),
        ('land_classifications', '0001_initial'),
        ('sites', '0002_alter_site_data_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_data',
            options={'ordering': ['-version']},
        ),
        migrations.AlterModelOptions(
            name='site_images',
            options={'ordering': ['layer_tag', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='site_species_recommendation',
            options={'ordering': ['priority_rank']},
        ),
        migrations.AlterField(
            model_name='site_data',
            name='field_assessment_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='site_data',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='site_data',
            name='site_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sites',
            name='center_coordinate',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sites',
            name='marker_coordinate',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='ndvi_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='reforestation_area',
            field=models.ForeignKey(help_text='Parent area container.', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='reforestation_areas.reforestation_areas'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='total_area_hectares',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sites',
            name='total_seedlings_planted',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SiteMetaDataVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verified_security_concerns', models.JSONField(blank=True, null=True)),
                ('verified_accessibility', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('draft', 'Draft'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('referenced_assessment_ids', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_verification', to='sites.sites')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
                ('verified_land_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sites', to='land_classifications.landclassification')),
            ],
            options={
                'verbose_name': 'Site Meta Data Verification',
                'verbose_name_plural': 'Site Meta Data Verifications',
            },
        ),
        migrations.CreateModel(
            name='Potential_sites',
            fields=[
                ('potential_sites_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('polygon_coordinates', models.JSONField(blank=True, null=True)),
                ('area_hectares', models.FloatField(default=0)),
                ('avg_ndvi', models.FloatField(default=0)),
                ('suitability_score', models.FloatField(default=0)),
                ('ndvi_threshold', models.FloatField(default=0.41)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, help_text='Linked to official Site upon consolidation. Null if still just a raw marker.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potential_sites', to='sites.sites')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitDocument',
            fields=[
                ('permit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_assessment_id', models.BigIntegerField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('land_title', 'Land Title'), ('tax_declaration', 'Tax Declaration'), ('barangay_clearance', 'Barangay Clearance'), ('lgu_endorsement', 'LGU Endorsement'), ('denr_permit', 'DENR Permit'), ('landowner_consent', 'Landowner Consent'), ('other', 'Other')], max_length=30)),
                ('permit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='permits/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_documents', to='sites.sites')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Permit Documents',
                'ordering': ['site', '-uploaded_at'],
            },
        ),
    ]
