# Generated by Django 4.2.30 on 2026-06-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_data_options_alter_site_images_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
