# Generated by Django 4.2.30 on 2026-06-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('sites', '0004_sites_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVerifiedAnimal',
            fields=[
                ('site_verified_animal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this animal observation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_verification_relations', to='animals.animal')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_relations', to='sites.sitemetadataverification')),
            ],
            options={
                'verbose_name': 'Site Verified Animal',
                'verbose_name_plural': 'Site Verified Animals',
                'db_table': 'site_verified_animals',
                'ordering': ['-created_at'],
                'unique_together': {('verification', 'animal')},
            },
        ),
        migrations.AddField(
            model_name='sitemetadataverification',
            name='verified_animals',
            field=models.ManyToManyField(blank=True, help_text='Animals verified by admin for this site', related_name='verified_sites', through='sites.SiteVerifiedAnimal', to='animals.animal'),
        ),
    ]
