# Generated by Django 4.2.30 on 2026-06-26 10:57

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_siteverifiedanimal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdocument',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='site_images',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
