# Generated by Django 4.2.30 on 2026-06-26 10:59

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_permitdocument_file_alter_site_images_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdocument',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])], verbose_name='file'),
        ),
    ]
