# Generated by Django 4.2.30 on 2026-07-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_permitdocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='permitdocument',
            name='permit_number',
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='notes',
            field=models.TextField(blank=True, help_text='Details, reference numbers, or notes regarding this document/permit.', null=True),
        ),
        migrations.AlterField(
            model_name='permitdocument',
            name='document_type',
            field=models.CharField(choices=[('land_title', 'Land Title'), ('tax_declaration', 'Tax Declaration'), ('other', 'Other')], max_length=30),
        ),
    ]
