# Generated by Django 4.2.30 on 2026-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_remove_permitdocument_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='center_coordinate',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='ndvi_value',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='total_seedlings_planted',
        ),
        migrations.AlterField(
            model_name='sites',
            name='marker_coordinate',
            field=models.JSONField(blank=True, help_text='Single [lat, lng] coordinate for the site marker/pin location.', null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, help_text='Array of [lat, lng] coordinates defining the site boundary.', null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='total_area_hectares',
            field=models.FloatField(default=0.0, help_text='Calculated area from polygon coordinates in hectares.'),
        ),
    ]
