# Generated by Django 4.2.30 on 2026-09-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_remove_sites_center_coordinate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='monitoring_status',
            field=models.CharField(choices=[('available', 'Available for New Program'), ('reserved', 'Reserved - Under Review'), ('under_monitoring', 'Under Active Monitoring'), ('completed', 'Program Completed'), ('failed', 'Program Failed'), ('onhold', 'On Hold')], db_index=True, default='available', help_text='Operational status for monitoring lifecycle and queueing', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
