# Generated by Django 4.2.30 on 2026-09-14 14:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_sites_monitoring_status_alter_sites_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main cover image for the site (Recommended: 16:9 ratio, max 5MB).', max_length=255, null=True, verbose_name='image'),
        ),
    ]
