# Generated by Django 4.2.30 on 2026-09-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reforestation_areas', '0005_reforestation_areas_barangay'),
        ('sites', '0011_sites_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='reforestation_area',
            field=models.ForeignKey(help_text='Parent area container.', on_delete=django.db.models.deletion.RESTRICT, related_name='sites', to='reforestation_areas.reforestation_areas'),
        ),
    ]
