# Generated by Django 4.2.30 on 2026-05-13 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('classification', models.CharField(choices=[('old', 'Old'), ('new', 'new')], default='old', max_length=50)),
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('for_evaluation', 'For Evaluation'), ('for_head', 'For Head'), ('accepted', 'Accepted'), ('agreed', 'Agreed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('under_monitoring', 'Under Monitoring'), ('completed', 'Completed')], default='save_draft', max_length=50)),
                ('orientation_date', models.DateField(blank=True, null=True)),
                ('project_duration', models.IntegerField(blank=True, help_text='Project duration in days', null=True)),
                ('maintenance_plan', models.FileField(blank=True, null=True, upload_to='application_maintenance_plans/')),
                ('agreement_image', models.ImageField(blank=True, null=True, upload_to='agreements/')),
                ('total_members', models.IntegerField(blank=True, null=True)),
                ('total_request_seedling', models.IntegerField(default=50, help_text='Total seedlings requested', validators=[django.core.validators.MaxValueValidator(50)])),
                ('total_seedling_provided', models.IntegerField(default=0, help_text='Total seedlings provided')),
                ('total_area_planted', models.DecimalField(decimal_places=2, default=0, help_text='Total area planted (in hectares)', max_digits=10)),
                ('total_seedling_survived', models.IntegerField(default=0, help_text='Total seedlings survived')),
                ('total_seedling_planted', models.IntegerField(default=0, help_text='Total seedlings actually planted')),
                ('confirmed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='sites.sites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance_report',
            fields=[
                ('maintenance_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('maintenance_report_file', models.FileField(blank=True, null=True, upload_to='maintenance_reports/')),
                ('total_member_present', models.IntegerField(blank=True, null=True)),
                ('group_picture', models.ImageField(blank=True, null=True, upload_to='maintenance_report_group_picture/')),
                ('total_seedling_planted', models.IntegerField(default=0, help_text='Total seedlings planted in this report period')),
                ('total_seedling_survived', models.IntegerField(default=0, help_text='Total seedlings survived in this report period')),
                ('total_area_planted', models.DecimalField(decimal_places=2, default=0, help_text='Total area planted in this report period (in hectares)', max_digits=10)),
                ('total_owned_seedling_planted', models.IntegerField(default=0, help_text='Total owned seedlings planted')),
                ('status', models.CharField(choices=[('for_evaluation', 'For Evaluation'), ('for_head', 'For Head'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='continue', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to='tree_planting_programs.application')),
            ],
            options={
                'verbose_name': 'Maintenance Report',
                'verbose_name_plural': 'Maintenance Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeedlingMax',
            fields=[
                ('seedling_id', models.AutoField(primary_key=True, serialize=False)),
                ('max', models.IntegerField(help_text='Maximum number of seedlings allowed')),
                ('min', models.IntegerField(help_text='Minimum number of seedlings allowed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seedling Max',
                'verbose_name_plural': 'Seedling Max Limits',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('status_layer', models.CharField(choices=[('new_program', 'New program'), ('report', 'Report')], default='new_program', max_length=50)),
                ('reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for rejection/cancellation')),
                ('status', models.CharField(choices=[('for_evaluation', 'For Evaluation'), ('for_head', 'For Head'), ('accepted', 'Accepted'), ('agreed', 'Agreed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('under_monitoring', 'Under Monitoring'), ('completed', 'Completed')], default='for_evaluation', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='tree_planting_programs.application')),
                ('maintenance_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='tree_planting_programs.maintenance_report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Reason',
                'verbose_name_plural': 'Reasons',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['application', 'status'], name='tree_planti_applica_9f2172_idx'), models.Index(fields=['user', 'status'], name='tree_planti_user_id_e9ad16_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('maintenance_alert', 'Maintenance Alert'), ('maintenance_report', 'Maintenance Report'), ('application_update', 'Application Update'), ('general', 'General')], default='general', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='tree_planti_user_id_4bbc78_idx'), models.Index(fields=['created_at'], name='tree_planti_created_7e2603_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='maintenance_report',
            index=models.Index(fields=['application', 'status'], name='tree_planti_applica_7830e6_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance_report',
            index=models.Index(fields=['created_at'], name='tree_planti_created_6b09ff_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='tree_planti_status_e8fe49_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='tree_planti_created_53bb9e_idx'),
        ),
    ]
