# Generated by Django 4.2.30 on 2026-05-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_planting_programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('progress_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_survived_plants', models.IntegerField(default=0, help_text='Number of plants that survived')),
                ('no_dead_plants', models.IntegerField(default=0, help_text='Number of plants that died')),
                ('proof_image_monitor_required', models.ImageField(blank=True, help_text='Proof images of monitoring', null=True, upload_to='progress_report_proof_images/')),
                ('description', models.TextField(blank=True, help_text='Additional notes about progress', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Progress Report',
                'verbose_name_plural': 'Progress Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeedlingRequest',
            fields=[
                ('maintenance_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Additional details about seedling request', null=True)),
                ('request_file', models.FileField(blank=True, help_text='Supporting documents for seedling request', null=True, upload_to='seedling_request_files/')),
                ('no_request_seedling', models.IntegerField(default=0, help_text='Number of seedlings requested')),
                ('seedling_type', models.JSONField(default=dict, help_text="JSON format: {'mahogany': 30, 'narra': 20}")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason_accepted', models.TextField(blank=True, help_text='Reason/notes when accepted', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seedling Request',
                'verbose_name_plural': 'Seedling Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='maintenance_report',
            name='application',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='SeedlingMax',
        ),
        migrations.RemoveField(
            model_name='application',
            name='total_area_planted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='total_request_seedling',
        ),
        migrations.RemoveField(
            model_name='application',
            name='total_seedling_planted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='total_seedling_provided',
        ),
        migrations.RemoveField(
            model_name='application',
            name='total_seedling_survived',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='maintenance_report',
        ),
        migrations.AlterField(
            model_name='application',
            name='agreement_image',
            field=models.ImageField(blank=True, help_text='Signed agreement image', null=True, upload_to='agreements/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='classification',
            field=models.CharField(choices=[('old', 'Old'), ('new', 'New')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='confirmed_at',
            field=models.DateField(blank=True, help_text='Date when Head confirmed the application', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='maintenance_plan',
            field=models.FileField(blank=True, help_text='Maintenance plan uploaded by tree grower', null=True, upload_to='application_maintenance_plans/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='orientation_date',
            field=models.DateField(blank=True, help_text='Assigned by DataManager during evaluation', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('for_evaluation', 'For Evaluation'), ('for_head', 'For Head'), ('accepted', 'Accepted'), ('agreed', 'Agreed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('under_monitoring', 'Under Monitoring'), ('completed', 'Completed')], default='for_evaluation', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_members',
            field=models.IntegerField(blank=True, help_text='Total members in the tree grower group', null=True),
        ),
        migrations.AlterField(
            model_name='reason',
            name='reason',
            field=models.TextField(help_text='Reason for rejection/cancellation/approval'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='status_layer',
            field=models.CharField(choices=[('new_program', 'New Program'), ('report', 'Report')], default='new_program', max_length=50),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='tree_planti_user_id_5bf2ac_idx'),
        ),
        migrations.DeleteModel(
            name='Maintenance_report',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='seedlingrequest',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seedling_requests', to='tree_planting_programs.application'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='tree_planting_programs.application'),
        ),
        migrations.AddIndex(
            model_name='seedlingrequest',
            index=models.Index(fields=['application', 'status'], name='tree_planti_applica_2b8f92_idx'),
        ),
        migrations.AddIndex(
            model_name='seedlingrequest',
            index=models.Index(fields=['created_at'], name='tree_planti_created_fb6758_idx'),
        ),
        migrations.AddIndex(
            model_name='progressreport',
            index=models.Index(fields=['application', 'status'], name='tree_planti_applica_08c33b_idx'),
        ),
        migrations.AddIndex(
            model_name='progressreport',
            index=models.Index(fields=['created_at'], name='tree_planti_created_3711c6_idx'),
        ),
    ]
