# Generated by Django 4.2.30 on 2026-05-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_planting_programs', '0002_progressreport_seedlingrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('for_evaluation', 'For Evaluation'), ('for_head', 'For Head'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='for_evaluation', max_length=50),
        ),
        migrations.AlterField(
            model_name='seedlingrequest',
            name='seedling_type',
            field=models.JSONField(blank=True, default=dict, help_text="JSON format: {'mahogany': 30, 'narra': 20}", null=True),
        ),
    ]
