# Generated by Django 4.2.30 on 2026-05-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_planting_programs', '0003_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedlingrequest',
            name='seedling_type',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
