# Generated by Django 4.2.30 on 2026-06-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_siteverifiedanimal_and_more'),
        ('tree_species', '0001_initial'),
        ('tree_planting_programs', '0004_alter_seedlingrequest_seedling_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReportSpecies',
            fields=[
                ('report_species_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_survived', models.IntegerField(default=0, help_text='Number of plants of this species that survived')),
                ('no_dead', models.IntegerField(default=0, help_text='Number of plants of this species that died')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Progress Report Species',
                'verbose_name_plural': 'Progress Report Species',
                'ordering': ['-no_survived'],
            },
        ),
        migrations.CreateModel(
            name='SeedlingRequestSpecies',
            fields=[
                ('seedling_species_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, help_text='Number of seedlings of this species')),
                ('provided_by', models.CharField(default='ENRO Nursery', help_text='Source/provider of the seedlings', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seedling Request Species',
                'verbose_name_plural': 'Seedling Request Species',
                'ordering': ['-quantity'],
            },
        ),
        migrations.RenameField(
            model_name='seedlingrequest',
            old_name='maintenance_report_id',
            new_name='seedling_request_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='project_duration',
        ),
        migrations.RemoveField(
            model_name='application',
            name='total_members',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='no_dead_plants',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='no_survived_plants',
        ),
        migrations.RemoveField(
            model_name='seedlingrequest',
            name='seedling_type',
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_orientation_date',
            field=models.DateField(blank=True, help_text='Orientation date proposed by returning tree grower', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_site',
            field=models.ForeignKey(blank=True, help_text='Site proposed by returning tree grower (nullable for first-timers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_applications', to='sites.sites'),
        ),
        migrations.AddField(
            model_name='application',
            name='total_treegrowers_will_participate',
            field=models.IntegerField(default=2, help_text='Total tree growers who will participate (minimum 2)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='classification',
            field=models.CharField(choices=[('new', 'New (First-Time)'), ('old', 'Returning')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='orientation_date',
            field=models.DateField(blank=True, help_text='Final orientation date assigned by DataManager', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Final site assigned by DataManager', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='sites.sites'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('for_evaluation', 'For Evaluation'), ('for_head', 'For Head Approval'), ('accepted', 'Accepted'), ('under_monitoring', 'Under Monitoring'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('failed', 'Failed')], default='for_evaluation', max_length=50),
        ),
        migrations.AlterField(
            model_name='reason',
            name='status',
            field=models.CharField(choices=[('for_evaluation', 'For Evaluation'), ('for_head', 'For Head'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('under_monitoring', 'Under Monitoring'), ('completed', 'Completed'), ('failed', 'Failed')], default='for_evaluation', max_length=50),
        ),
        migrations.AlterField(
            model_name='reason',
            name='status_layer',
            field=models.CharField(choices=[('new_program', 'New Program'), ('report', 'Report'), ('seedling_request', 'Seedling Request')], default='new_program', max_length=50),
        ),
        migrations.AlterField(
            model_name='seedlingrequest',
            name='no_request_seedling',
            field=models.IntegerField(default=0, help_text='Total number of seedlings requested (summary)'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['classification'], name='tree_planti_classif_695050_idx'),
        ),
        migrations.AddField(
            model_name='seedlingrequestspecies',
            name='seedling_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seedling_species', to='tree_planting_programs.seedlingrequest'),
        ),
        migrations.AddField(
            model_name='seedlingrequestspecies',
            name='tree_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seedling_requests', to='tree_species.tree_species'),
        ),
        migrations.AddField(
            model_name='progressreportspecies',
            name='progress_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_species', to='tree_planting_programs.progressreport'),
        ),
        migrations.AddField(
            model_name='progressreportspecies',
            name='tree_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='tree_species.tree_species'),
        ),
        migrations.AddConstraint(
            model_name='seedlingrequestspecies',
            constraint=models.UniqueConstraint(fields=('seedling_request', 'tree_species'), name='unique_species_per_seedling_request'),
        ),
        migrations.AddConstraint(
            model_name='progressreportspecies',
            constraint=models.UniqueConstraint(fields=('progress_report', 'tree_species'), name='unique_species_per_progress_report'),
        ),
    ]
