# Generated by Django 4.2.30 on 2026-06-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_treegrowergroup_remove_organization_users_and_more'),
        ('tree_planting_programs', '0005_progressreportspecies_seedlingrequestspecies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='accounts.user'),
        ),
    ]
