# Generated by Django 4.2.30 on 2026-06-26 11:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_planting_programs', '0006_alter_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='agreement_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Signed agreement image', max_length=255, null=True, verbose_name='agreement_image'),
        ),
        migrations.AlterField(
            model_name='application',
            name='maintenance_plan',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Maintenance plan uploaded by tree grower', max_length=255, null=True, verbose_name='maintenance_plan'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='proof_image_monitor_required',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Proof images of monitoring', max_length=255, null=True, verbose_name='proof_image_monitor_required'),
        ),
        migrations.AlterField(
            model_name='seedlingrequest',
            name='request_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Supporting documents for seedling request', max_length=255, null=True, verbose_name='request_file'),
        ),
    ]
