# Generated by Django 4.2.30 on 2026-06-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_planting_programs', '0007_alter_application_agreement_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedlingrequest',
            name='request_file',
        ),
    ]
