# Generated by Django 4.2.30 on 2026-07-22 06:06

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_notification_title'),
        ('tree_planting_programs', '0008_remove_seedlingrequest_request_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedlingrequest',
            name='assigned_inspector',
            field=models.ForeignKey(blank=True, help_text='Inspector assigned to verify receipt', limit_choices_to={'user_role': 'OnsiteInspector'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_seedling_requests', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='seedlingrequest',
            name='fulfillment_type',
            field=models.CharField(blank=True, choices=[('pickup', 'Grower Pickup'), ('deliver', 'Delivered to Site')], help_text='How the seedlings will be received', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seedlingrequest',
            name='proof_of_delivery',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Photo proof of seedling handover/delivery', max_length=255, null=True, verbose_name='proof_of_delivery'),
        ),
        migrations.AddField(
            model_name='seedlingrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for rejection or cancellation', null=True),
        ),
        migrations.AddField(
            model_name='seedlingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seedlingrequest',
            name='reason_accepted',
            field=models.TextField(blank=True, help_text='Notes when accepted (Legacy)', null=True),
        ),
        migrations.AlterField(
            model_name='seedlingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='seedlingrequest',
            index=models.Index(fields=['assigned_inspector', 'status'], name='tree_planti_assigne_2cb75c_idx'),
        ),
    ]
