# Generated by Django 4.2.30 on 2026-07-22 14:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_planting_programs', '0009_seedlingrequest_assigned_inspector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Progress Report (Monitoring Visit)', 'verbose_name_plural': 'Progress Reports (Monitoring Visits)'},
        ),
        migrations.AddField(
            model_name='progressreport',
            name='agreement_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Signed agreement image uploaded during initial orientation visit', max_length=255, null=True, verbose_name='agreement_image'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='orientation_conducted',
            field=models.BooleanField(default=False, help_text='Check if orientation was successfully conducted (Initial visit only)'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='visit_type',
            field=models.CharField(choices=[('initial', 'Initial Visit (Orientation & Baseline)'), ('ongoing', 'Ongoing Monitoring Visit')], default='initial', max_length=20),
        ),
        migrations.AddField(
            model_name='progressreportspecies',
            name='no_added_by_grower',
            field=models.IntegerField(default=0, help_text='Extra seedlings added by tree grower from their own source during THIS visit'),
        ),
        migrations.AddField(
            model_name='progressreportspecies',
            name='no_planted',
            field=models.IntegerField(default=0, help_text='Number of official seedlings planted (baseline, set in initial visit)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='agreement_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='[DEPRECATED] Signed agreement image - now stored in ProgressReport', max_length=255, null=True, verbose_name='agreement_image'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('for_evaluation', 'For Evaluation'), ('for_head', 'For Head Approval'), ('accepted', 'Accepted - Ready for Orientation'), ('under_monitoring', 'Under Monitoring'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('failed', 'Failed')], default='for_evaluation', max_length=50),
        ),
        migrations.AlterField(
            model_name='progressreportspecies',
            name='no_dead',
            field=models.IntegerField(default=0, help_text='Number of plants of this species that died (cumulative or per visit)'),
        ),
        migrations.AlterField(
            model_name='progressreportspecies',
            name='no_survived',
            field=models.IntegerField(default=0, help_text='Current number of plants of this species that survived'),
        ),
        migrations.AddIndex(
            model_name='progressreport',
            index=models.Index(fields=['application', 'visit_type'], name='tree_planti_applica_69a070_idx'),
        ),
    ]
