# Generated by Django 4.2.30 on 2026-09-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_remove_sites_center_coordinate_and_more'),
        ('tree_planting_programs', '0010_alter_progressreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='site',
            field=models.ForeignKey(help_text='Site being monitored (required)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='sites.sites'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Linked application (null if monitoring without active program)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_reports', to='tree_planting_programs.application'),
        ),
        migrations.AddIndex(
            model_name='progressreport',
            index=models.Index(fields=['site', 'status'], name='tree_planti_site_id_6e2b29_idx'),
        ),
        migrations.AddIndex(
            model_name='progressreport',
            index=models.Index(fields=['site', 'visit_type'], name='tree_planti_site_id_07d8d8_idx'),
        ),
    ]
