# Generated by Django 4.2.30 on 2026-09-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_planting_programs', '0011_progressreport_site_alter_progressreport_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='visit_type',
            field=models.CharField(choices=[('initial', 'Initial Visit (Orientation & Baseline)'), ('ongoing', 'Ongoing Monitoring Visit'), ('inactive_check', 'Inactive Site Check')], default='initial', max_length=20),
        ),
    ]
