# Generated by Django 4.2.30 on 2026-09-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_planting_programs', '0012_alter_progressreport_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Position in queue (1=under review by Head, 2+=reserved/waiting)', null=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['site', 'queue_position'], name='tree_planti_site_id_586280_idx'),
        ),
    ]
